---
- name: Deploy NGINX Web Server with Custom Homepage
  hosts: webservers
  become: yes
  gather_facts: yes

  vars:
    # Supported OS families
    supported_os_families:
      - RedHat
      - Debian

    # Web server paths
    web_root: /usr/share/nginx/html
    index_file: "{{ web_root }}/index.html"
    local_index_path: files/index.html

  pre_tasks:
    - name: Validate supported operating system
      assert:
        that:
          - ansible_os_family in supported_os_families
        fail_msg: >-
          Unsupported OS family: {{ ansible_os_family }}.
          Supported families: {{ supported_os_families | join(', ') }}.
        success_msg: "OS family {{ ansible_os_family }} is supported."

    - name: Set package and service names
      set_fact:
        nginx_package: nginx
        nginx_service: nginx

  tasks:
    - name: Install NGINX
      package:
        name: "{{ nginx_package }}"
        state: present
      tags: nginx

    - name: Ensure NGINX is running and enabled
      service:
        name: "{{ nginx_service }}"
        state: started
        enabled: yes
      tags: nginx

    - name: Upload custom index.html
      copy:
        src: "{{ local_index_path }}"
        dest: "{{ index_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart NGINX
      tags: content

  handlers:
    - name: Restart NGINX
      service:
        name: "{{ nginx_service }}"
        state: restarted
